version: "2"
run:
  tests: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: ""
linters:
  default: none
  enable:
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - exptostd
    - gocheckcompilerdirectives
    - gocyclo
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nestif
    - nilnesserr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - staticcheck
    - tagalign
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    gocyclo:
      min-complexity: 30
    gosec:
      excludes:
        - G101
        - G115
        - G401
        - G402
        - G404
        - G405
        - G406
        - G501
        - G502
        - G503
        - G504
        - G505
        - G506
        - G507
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    nestif:
      min-complexity: 10
    misspell:
      locale: US
    staticcheck:
      checks:
        [
          "all",
          "-QF1001",
          "-ST1000",
          "-ST1003",
          "-ST1016",
          "-SA1019",
          "-ST1020",
          "-ST1021",
          "-ST1022",
        ]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
