site_name: AILERON | Go
site_url: https://aileron-projects.github.io/go
site_description: AILERON Projects | Go standard package extensions.
site_author: AILERON Projects Community
copyright: Copyright &copy; 2025 AILERON Projects Community.
repo_name: aileron-projects/go
repo_url: https://github.com/aileron-projects/go

docs_dir: "./website"
strict: true

extra_css:
  - ./mkdocs.css
extra_javascript:
  - ./mkdocs.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  locale: en
  highlightjs: true
  logo: static/aileron.svg
  favicon: static/aileron.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.path
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - toc.follow

plugins:
  - search
  - tags
  - exclude:
      regex:
        - ".*/README.md"
  - i18n:
      languages:
        - locale: en
          name: "English"
          default: true
        - locale: ja
          name: "日本語"

markdown_extensions:
  - attr_list
  - smarty
  - admonition
  - meta
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "./website"
      check_paths: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: false
  version:
    provider: mike
  # analytics:
  #   provider: google
  #   property: G-XXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aileron-projects/go

nav:
  - Docs:
      - overview: docs/overview/index.md
      - getting-started: docs/getting-started/index.md
      - community: docs/community/index.md
      - contributing: docs/contributing/index.md
  - References:
      - cron: references/cron/index.md
      - debug: references/debug/index.md
      - env: references/env/index.md
      - logging: references/logging/index.md
      - rate: references/rate/index.md
      - tcp: references/tcp/index.md
      - udp: references/udp/index.md
  - Examples: examples/index.md
  - "": index.md
