name: Check Suite Scheduled

on:
  workflow_dispatch: {}
  workflow_call: {}
  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  vulnerability:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: aileron-projects/_scripts/.github/actions/govulncheck@main
