name: Deploy Pages

on:
  push: {}
    # branches:
    #   - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: build
        run: |
          cd docs/
          pip install mkdocs mkdocs-material mkdocs-material-extensions mkdocs-static-i18n
          mkdocs build
      - name: Upload pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
